___

<a href='https://www.udemy.com/user/joseportilla/'><img src='../Pierian_Data_Logo.png'/></a>
___
<center><em>Content Copyright by Pierian Data</em></center>

# PDFs and Spreadsheets Puzzle Exercise

Let's test your skills, the files needed for this puzzle exercise

You will need to work with two files for this exercise and solve the following tasks:

* Task One: Use Python to extract the Google Drive link from the .csv file. (Hint: Its along the diagonal from top left to bottom right).
* Task Two: Download the PDF from the Google Drive link (we already downloaded it for you just in case you can't download from Google Drive) and find the phone number that is in the document. Note: There are different ways of formatting a phone number!

## Task One: Grab the Google Drive Link from .csv File

In [1]:
import csv

In [2]:
f = open('Exercise_Files/find_the_link.csv',encoding="utf-8")
data = csv.reader(f)
data_lines = list(data)

#get header & first 4 lines
for line in data_lines[:5]:
    print(line)

['h', '53', '24', '46', '4', '11', '3', '35', '17', '52', '9', '60', '26', '60', '72', '39', '11', '80', '86', '66', '59', '9', '41', '33', '11', '42', '69', '74', '91', '61', '5', '69', '17', '17', '78', '6', '51', '54', '54', '94', '47', '37', '0', '16', '71', '6', '83', '7', '6', '38', '61', '18', '68', '15', '2', '81', '49', '5', '17', '21', '36', '63', '38', '24', '3', '99']
['85', 't', '31', '54', '60', '22', '77', '39', '93', '38', '31', '16', '29', '27', '8', '35', '0', '54', '84', '21', '47', '37', '66', '83', '26', '22', '68', '25', '44', '81', '27', '68', '17', '63', '13', '99', '38', '43', '87', '83', '73', '88', '67', '5', '12', '10', '7', '58', '64', '56', '53', '88', '96', '20', '7', '85', '94', '23', '14', '79', '24', '27', '90', '40', '27', '8']
['22', '98', 't', '83', '33', '53', '66', '13', '81', '53', '60', '52', '45', '51', '39', '98', '14', '94', '68', '5', '99', '62', '68', '95', '50', '81', '64', '58', '96', '1', '71', '4', '60', '57', '84', '39', '5', '24', '79

From what I can see is a `https` spelled out in diagonal.

In [3]:
len(data_lines)

66

In [4]:
len('https://drive.google.com/open?id=1G6SEgg018UB4_4xsAJJ5TdzrhmXipr4Q')

66

The number of lines in the csv file is also equal to the solution we are given. So, we need to create a list and append it with diagonal imputs from 0 to 66. After we create the list, we will join it into a single link.

In [5]:
# empty list
link = []

# a for loop to iterate through the list
# we can use enumerate here

for row_num, data in enumerate(data_lines):
    link.append(data[row_num])

In [6]:
# using joing to avoid printing out a huge list

''.join(link)

'https://drive.google.com/open?id=1G6SEgg018UB4_4xsAJJ5TdzrhmXipr4Q'

In [7]:
# THe correct result is shown below, if you can't download from Google Drive, 
# we added the PDF file to the Exercise_Files folder already

print("https://drive.google.com/open?id=1G6SEgg018UB4_4xsAJJ5TdzrhmXipr4Q")

https://drive.google.com/open?id=1G6SEgg018UB4_4xsAJJ5TdzrhmXipr4Q


## Task Two: Download the PDF from the Google Drive link and find the phone number that is in the document. 

In [8]:
import PyPDF2

In [15]:
# At first, we open the file in read binary

f = open('Exercise_Files/Find_the_Phone_Number.pdf','rb')

# After that, we read it

pdf_reader = PyPDF2.PdfFileReader(f)

In [16]:
# Get the first page
page_one = pdf_reader.getPage(0)

# Extracting the text
page_one_text = page_one.extractText()

page_one_text

"Business Deliverables\n \n \n \nStaff engagement touch base yet can I just chime in on that one draw a line in the sand \nthis proposal is a win\n-\nwin situation which will cause a stellar paradigm shift, and \nproduce a multi\n-\nfold increase in deliverables but \nfuture\n-\nproof. I dont care if you got some \ncopy, why you dont use officeipsumcom or something like that ? low\n-\nhanging fruit beef \nup, and optimize for search or we need to leverage our synergies. We need to make the \nnew version clean and sexy bells and whist\nles, so meeting assassin, and execute . \nBaseline the procedure and samepage your department push back yet strategic high\n-\nlevel 30,000 ft view powerPointless, but deliverables nor circle back. Paddle on both \nsides conversational content win\n-\nwin\n-\nwin nor pig \nin a python overcome key issues to \nmeet key milestones. Personal development crisp ppt deep dive. Can we parallel path \nblue sky and this proposal is a win\n-\nwin situation which wi

No phone number in the first page. That means, the phone number might be either on the last page or hidden in the text. Lets try first grabbing the last page.

In [19]:
# Finding out the number of pages

pdf_reader.numPages

17

In [20]:
# Get the last page
last_page = pdf_reader.getPage(16)

# Extracting the text
last_page_text = last_page.extractText()

last_page_text

"line in the sand, for zeitgeist. Per my previous email we need to harvest synergy effects. \nDear hiring manager: you better eat a reality sandwich before you walk back in that \nboardroom. Ladder up / ladder back to the strategy cloud native container based\n \n(let's \nnot try to) boil the ocean (here/there/everywhere), strategic fit. Game\n-\nplan target rich \nenvironment for bench mark. Hammer out game\n-\nplan it's a simple lift and shift job. Put \nin in a deck for our standup today manage expectations nor baseline the \nprocedure and \nsamepage your department, but optimize the fireball. Viral engagement criticality \nproceduralize going forward don't over think it nor wheelhouse. Synergestic actionables \ndrop\n-\ndead date, so collaboration through advanced technlogy horsehead of\nfer. \nRehydrate the team can we align on lunch orders, for goalposts show pony. Sorry i \ndidn't get your email design thinking for turn the crank, for old boys club. Those options \nare already b

So, there is no phone number on the last page. It has to be in the text. Problem is that we don't know the actual pattern of the phone number. We can only assume it's a series of numbers, either no separator or separated by either a space or a point in order to be more easly read. First, we will try to grab all the text. Afterwards, using regex, we will try and find a pattern that has 3-10 digits and work from there.

In [21]:
import re

In [33]:
pattern = r"\d{3,10}"

In [26]:
# String object that will hold our text
text = ''

# Loop to go through the pages and grab text
for n in range(pdf_reader.numPages):
    
    page = pdf_reader.getPage(n)
    page_text = page.extractText()
    
    text = text+' '+ page_text #concatenation

In [34]:
phone = re.findall(pattern, text)
print(phone)

['000', '000', '000', '505', '503', '4455']


We can make out that the number is `505 503 445`. Since we don't know the exact pattern, we will use wildcard symbols in our regex in order to get that actual phone number.

In [36]:
pattern = r"\d{3}.\d{3}.\d{4}"

phone = re.findall(pattern, text)
print(phone[0])

505.503.4455


In [1]:
# You should get this phone number
# 505 503 4455